name: rawenergy
favicon: null
layout_spectrum: 0.17797296424396336
typography_spectrum: 0.9463746189139783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.016334098996594548
  lightness: 0.6344553171657026
  saturation: 0.051274503814056516
  rhythmicContrast: 0.5642075268551707
purpose: []
